# Generated by Django 4.2.6 on 2023-11-06 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_image', models.ImageField(upload_to='media/category')),
                ('category_desc', models.TextField()),
                ('soft_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(max_length=200)),
                ('old_price', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('colors', models.CharField(blank=True, max_length=100, null=True)),
                ('sizes', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('product_image1', models.ImageField(blank=True, null=True, upload_to='media')),
                ('product_image2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('product_image3', models.ImageField(blank=True, null=True, upload_to='media')),
                ('product_image4', models.ImageField(blank=True, null=True, upload_to='media')),
                ('product_image5', models.ImageField(blank=True, null=True, upload_to='media')),
                ('quantity', models.IntegerField()),
                ('is_avialable', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is available')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('material', models.CharField(max_length=200)),
                ('special_feature', models.CharField(max_length=200)),
                ('fit_type', models.CharField(max_length=200)),
                ('shoe_width', models.IntegerField()),
                ('category', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
            ],
        ),
    ]
