# Generated by Django 4.2.6 on 2023-11-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/img1'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/img2'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/img3'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/img4'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image5',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/img5'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='media/profile/default.png', upload_to='media/profile'),
        ),
    ]
