# Generated by Django 4.2.6 on 2023-11-08 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='House_name',
            new_name='house_name',
        ),
    ]
