# Generated by Django 4.2.6 on 2023-11-20 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_wallet_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
