# Generated by Django 4.2.6 on 2023-11-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_productattribute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
