# Generated by Django 4.2.6 on 2023-11-30 09:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='profile',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='mainapp.profile'),
            preserve_default=False,
        ),
    ]
