# Generated by Django 4.2.6 on 2023-11-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_reviews_date_reviews_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='profile',
        ),
    ]
