# Generated by Django 4.2.6 on 2023-11-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_rename_date_reviews_created_at_reviews_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
