# Generated by Django 4.2.6 on 2023-12-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_remove_products_quantity_remove_products_sizes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='unlist',
            field=models.BooleanField(default=False),
        ),
    ]
