# Generated by Django 4.2.6 on 2023-11-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_offers_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='discount_value',
            field=models.CharField(max_length=100),
        ),
    ]
