# Generated by Django 4.2.6 on 2023-11-24 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_products_brand_name_alter_products_created_on_and_more'),
        ('adminapp', '0003_alter_offers_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offers',
            name='discount_on',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
