# Generated by Django 4.2.6 on 2023-11-24 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_products_brand_name_alter_products_created_on_and_more'),
        ('adminapp', '0004_offers_category_offers_discount_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.products'),
        ),
    ]
