# Generated by Django 4.2.6 on 2023-12-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
