# Generated by Django 4.2.6 on 2023-11-16 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0005_payment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
    ]
