# Generated by Django 4.2.6 on 2023-11-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0006_remove_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='Cancelled', max_length=100),
        ),
    ]
