# Generated by Django 4.2.6 on 2023-11-25 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0010_coupons_unlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupons',
            old_name='unlist',
            new_name='list',
        ),
    ]
