# Generated by Django 4.2.6 on 2023-11-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0011_rename_unlist_coupons_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='list',
            field=models.BooleanField(default=True),
        ),
    ]
