# Generated by Django 4.2.6 on 2023-11-25 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0012_alter_coupons_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupons',
            old_name='list',
            new_name='listed',
        ),
    ]
