# Generated by Django 4.2.6 on 2023-11-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0013_rename_list_coupons_listed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='listed',
        ),
        migrations.AddField(
            model_name='coupons',
            name='un_list',
            field=models.BooleanField(default=False),
        ),
    ]
