# Generated by Django 4.2.6 on 2023-12-02 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_remove_products_quantity_remove_products_sizes_and_more'),
        ('orderapp', '0015_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='variant',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='mainapp.productattribute'),
            preserve_default=False,
        ),
    ]
