# Generated by Django 4.2.6 on 2023-12-02 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0018_order_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='variant',
        ),
    ]
