# Generated by Django 4.2.6 on 2023-12-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0020_order_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='size',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
