# Generated by Django 4.2.6 on 2023-12-02 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_remove_products_quantity_remove_products_sizes_and_more'),
        ('orderapp', '0021_remove_order_size_orderproduct_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='variant',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='mainapp.productattribute'),
            preserve_default=False,
        ),
    ]
